services:
  elasticsearch:
    build:
      context: ./custom-elastic
      dockerfile: Dockerfile
    container_name: elasticsearch-test
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false   # disable auth for local testing
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.4
    container_name: kibana-test
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"

  tokenizer:
    image: vuthaihoc/coccoc-tokenizer:python-slim
    container_name: coccoc-tokenizer
    ports:
      - "1880:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1880/"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  es_data:
    driver: local
